### PR TITLE
Adds styles to fix scrolling behavior with submarine nested in sidebar

### LINKED ISSUE #486: Issue with nested Sidebar and Submarine
[This codepen](http://codepen.io/njlg/pen/xEKKpd?editors=0110) doesn't behave as expected on Safari or FF. It appears to be an issue with overflows, but I'm not 100% sure.

### PR DESCRIPTION
**Pull request by mute**
## PR Checklist

- Manually tested across supported browsers
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [x] IE11 (Win 7)
  - [x] Edge (Win 10)
- ~~Unit tests written (`common` at minimum)~~
- [x] PR has one of the `semver-` labels
- [ ] Two core team engineer approvals
- ~~One core team UX approval~~

Fixes #486

### CODE REVIEW

File: src/components/SplitHorizontal/SplitHorizontal.jsx [hunk 1]
```diff
@@ -387,6 +387,7 @@ const SplitHorizontal = createClass({
 					'&-is-animated': isAnimated,
 				}, className)}
 				style={{
+					display: 'flex',
```
Comment (jondlm) [inline src/components/SplitHorizontal/SplitHorizontal.jsx]: LGTM. @ogupte does this line up with what you were thinking?

Comment (ogupte) [inline src/components/SplitHorizontal/SplitHorizontal.jsx]: yeah looks good to me, not sure how i forgot to give both panes `overflow: 'auto'`, so this is a good catch!
