### PR TITLE
Sidebar: fix gripper icon centering

### LINKED ISSUE #801: Add a pixel to Sidebar gripper
Add a pixel to the Sidebar gripper area so that the gripper icon can be centered within the space. Currently the gripper icon is more toward the right of the space.

### PR DESCRIPTION
**Pull request by sodiumjoe**
fixes #801 

http://docspot.devnxs.net/projects/lucid/801-sidebar-gripper/

## PR Checklist

- Manually tested across supported browsers
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [ ] Edge (Win 10)
- ~~[ ] Unit tests written (`common` at minimum)~~
- [x] PR has one of the `semver-` labels
- [x] Two core team engineer approvals
- [x] One core team UX approval

### CODE REVIEW

File: src/components/Sidebar/Sidebar.jsx [hunk 1]
```diff
@@ -294,7 +294,10 @@ const Sidebar = createClass({
 						{barProps.children}
 					</div>
 				</BarPane>
-				<SplitVertical.Divider className={cx('&-Divider')}>
+				<SplitVertical.Divider
+					className={cx('&-Divider')}
+					style={{ width: '7px' }}
```
Comment (ogupte) [inline src/components/Sidebar/Sidebar.jsx]: `style={{ width: 7 }}`

also, why not set this in Sidebar.less?

Comment (sodiumjoe) [reply src/components/Sidebar/Sidebar.jsx]: because it's in inline style in `SplitVertical.Divider`

Comment (sodiumjoe) [reply src/components/Sidebar/Sidebar.jsx]: fixed

File: src/components/Sidebar/Sidebar.jsx [hunk 2]
```diff
@@ -294,7 +294,7 @@ const Sidebar = createClass({
 						{barProps.children}
 					</div>
 				</BarPane>
-				<SplitVertical.Divider className={cx('&-Divider')}>
+				<SplitVertical.Divider className={cx('&-Divider')} style={{ width: 7 }}>
```
Comment (ogupte) [inline src/components/Sidebar/Sidebar.jsx]: why does this need to be hardcoded in the render function rather than defined in Sidebar.less?

Comment (sodiumjoe) [reply src/components/Sidebar/Sidebar.jsx]: because in `SplitVertical`:

```
										style={{
											width: '6px',
											boxSizing: 'border-box',
											...dividerProps.style,
										}}
```

Comment (chrisdopuch) [reply src/components/Sidebar/Sidebar.jsx]: The problem is that the jsx styles in SplitVertical would overwrite styles from the Sidebar.less?

Comment (sodiumjoe) [reply src/components/Sidebar/Sidebar.jsx]: that's correct

Comment (ogupte) [reply src/components/Sidebar/Sidebar.jsx]: The intent of SplitVertical is to style the divider with a default width to be overwritten by a consumer like Sidebar...You could increase the specificity of the selector in less, but it's probably best to descrease the specificity in SplitVertical.less

In any case, this should work for now, but it should be fixed with better css patterns.

Comment (sodiumjoe) [reply src/components/Sidebar/Sidebar.jsx]: it's not a selector in less, it's an inline style in jsx. The only way to override it is to pass it in as a style.
