### PR TITLE
Refactor child-component.js and fix bug

### LINKED ISSUE #13: Fix child component bug and improve function names
There is a bug with `getAllAsProps` in the `child-components` file. We should also change some of the names of those functions to be more clear.

### PR DESCRIPTION
**Pull request by jondlm**
There was a bug that was caused by not filtering out `null` values in the old version of `getAllAsProps`, this was fixed by `.filter(x => x)`

### CODE REVIEW

File: src/util/child-component.js [hunk 1]
```diff
@@ -18,68 +18,82 @@ export function createChildComponent (definition={}) {
...
+					.filter(x => x) // remove falsey values
+					.value();
 
-			getAllAsProps(props, elements) {
-				let component = this;
-				return _.map(_.flatten([_.get(props, definition.propName, [])]), (childProp) => {
+				return _.map(currentProps, (childProp) => {
 					if (_.isPlainObject(childProp)) {
-						return _.assign({}, childProp, {children: childProp.children || childProp.text});
+						return childProp;
```
Comment (jondlm) [inline src/util/child-component.js]: I got rid of the `text` alias cause I thought it was confusing. We can always add it back if needed.

File: src/util/child-component.js [hunk 2]
```diff
@@ -18,68 +18,82 @@ export function createChildComponent (definition={}) {
...
-				let component = this;
-				return _.map(component.getAll(elements), 'props');
-			},
+			getOwnProps(parentProps) {
+				// Extract out the defined `childProps` from the parent class
+				const currentProps = _.chain(parentProps)
+					.get(definition.propName) // grab the prop we care about, e.g. "Child"
+					.thru(x => [x]) // wrap in an array
+					.flatten()
+					.filter(x => x) // remove falsey values
```
Comment (jondlm) [inline src/util/child-component.js]: This is the bug fix line

File: src/util/child-component.js [hunk 3]
```diff
@@ -18,68 +18,82 @@ export function createChildComponent (definition={}) {
...
-			 *	                          might have this type
-			 * @return {Array} `props` objects of elements with this component type
+			 * @param {object} parentProps - usually `this.props` that may contain a prop for the current component type
+			 * @return {array} - an array of normalized props
 			 */
-			getAllProps(elements) {
-				let component = this;
-				return _.map(component.getAll(elements), 'props');
-			},
+			getOwnProps(parentProps) {
```
Comment (jondlm) [inline src/util/child-component.js]: Broke out a new function to make the logic a little clearer

**Comment by ogupte** [comment]
looks good
