### PR TITLE
Fix issue with RadioGroup children

### LINKED ISSUE #262: InfoIcon won’t render next to the label of this radio component
Someone reported that the following snippet isn't working.

```<RadioGroup.RadioButton>
  <RadioGroup.Label>
    All
    <span>
      <InfoIcon isBadge={true} size={14}/>
    </span>
  </RadioGroup.Label>
</RadioGroup.RadioButton>
```

### PR DESCRIPTION
**Pull request by jondlm**
Fixes #262

## PR Checklist

- Manually tested across supported browsers
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [x] IE11 (Win 7)
  - [x] Edge (Win 10)
- [x] Unit tests written (`common` at minimum)
- [x] PR has one of the `semver-` labels
- [ ] Two core team engineer approvals
- ~~One core team UX approval~~

### CODE REVIEW

File: src/components/RadioGroup/RadioGroup.jsx [hunk 1]
```diff
@@ -114,24 +113,24 @@ const RadioGroup = createClass({
...
-								name={name}
-								onSelect={this.handleSelected}
-								Label={_.get(_.first(findTypes(radioButtonChildProp, RadioGroup.Label)), 'props.children', null)}
+							{...radioButtonChildProp}
+							isSelected={actualSelectedIndex === index}
+							key={index}
+							callbackId={index}
+							name={name}
+							onSelect={this.handleSelected}
+							Label={_.get(_.first(findTypes(radioButtonChildProp, RadioGroup.Label)), 'props', null)}
```
Comment (jondlm) [inline src/components/RadioGroup/RadioGroup.jsx]: This is the actual fix. Most everything else was just whitespace changes, and tests.
