### PR TITLE
fix ToolTip alignmentOffset

### LINKED ISSUE #306: ToolTips are busted
image

I suspect this is caused by a patch or minor bump in one of our dependencies. Not 100% on that thought. I'm seeing an error in the console:

```
Warning: `div` was passed a style object that has previously been mutated. Mutating `style` is deprecated. Consider cloning it beforehand. Check the `render` using <div>. Previous style: {minWidth: 116.609375, maxWidth: 200, opacity: 1, maxHeight: "none", left: 900.796875, top: NaN}. Mutated style: {minWidth: 116.609375, maxWidth: 200, opacity: 1, maxHeight: "none", left: 900.796875, top: NaN}
```

### PR DESCRIPTION
**Pull request by sodiumjoe**
fixes #306 

## PR Checklist

- [x] PR has one of the `semver-` labels
- [x] Two core team engineer approvals

Not sure why the desctucturing default assignment isn't working, but
this fixes it. Will revisit.

### CODE REVIEW

File: src/components/ContextMenu/ContextMenu.jsx [hunk 1]
```diff
@@ -354,6 +355,8 @@ const ContextMenu = createClass({
 		const flyoutElement = _.first(findTypes(this.props, ContextMenu.FlyOut));
 		const flyProps = _.get(flyoutElement, 'props', {});
 
+		if (_.isNaN(this.getFlyoutPosition().top)) { window.foo = true; }
```
Comment (ogupte) [inline src/components/ContextMenu/ContextMenu.jsx]: what does this do?

Comment (sodiumjoe) [inline src/components/ContextMenu/ContextMenu.jsx]: whoops, that was for debugging
