### PR TITLE
Fix SingleSelect in RadioGroup bug

### LINKED ISSUE #662: SingleSelect does not render properly inside RadioGroup.Label
In order to show/hide content underneath radio buttons (as they are selected), I tried using the RadioGroup component and placed selection-specific content inside the RadioGroup.Label component (with a conditional wrapper to specify whether or not it should be shown). Ex: 

```
<RadioGroup.RadioButton>
    <RadioGroup.Label>
        <span>{label}</span>
        { 
            isOptionOneSelected 
            ? <OptionOneContent />
            : null
        }
    </RadioGroup.Label>
</RadioGroup.RadioButton>
```

This generally works, but when I try to place a SingleSelect component inside RadioGroup.Label, the menu does not render when the SingleSelect is clicked. It works fine outside of RadioGroup, however. It doesn't work inside the RadioButtonLabeled component either.

### PR DESCRIPTION
**Pull request by jondlm**
Fixes #662

Detects if a body click was a `<label>` and doesn't trigger the on click
out handler if that's the case.

## PR Checklist

- Manually tested across supported browsers
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [x] IE11 (Win 7)
  - [x] Edge (Win 10)
- [x] Unit tests written (`common` at minimum)
- [x] PR has one of the `semver-` labels
- [ ] Two core team engineer approvals
- ~~One core team UX approval~~

### CODE REVIEW

File: src/components/ContextMenu/ContextMenu.jsx [hunk 1]
```diff
@@ -133,27 +133,46 @@ const ContextMenu = createClass({
...
+			},
+			refs: {
+				flyOutPortal,
+				target,
+			},
+		} = this;
+
+		if (onClickOut && flyOutPortal) {
+			const flyOutEl = flyOutPortal.portalElement.firstChild;
+			const wasALabelClick = event.target.nodeName === 'INPUT' && sharesAncestor(event.target, target, 'LABEL');
```
Comment (jondlm) [inline src/components/ContextMenu/ContextMenu.jsx]: I learned that `<label>`s fire a real click event with a target of the corresponding `INPUT`. This line checks to see if the event fired relates to an input and shares a label ancestor with the context menu target.

File: src/util/dom-helpers.js [hunk 2]
```diff
@@ -35,3 +35,30 @@ export function dispatchDOMEvent(node, eventName, assignedEventProps) {
...
+
+/**
+ * sharesAncestor
+ *
+ * Recursively looks at `node` and its parents for `findNodeName` and makes
+ * sure it contains `siblingNode`.
+ *
+ * @param {element} node - dom node to check if any of its ancestors are a `<label>`
+ * @param {element} siblingNode - dom node to see if it shares an ancestor
+ * @param {string} findNodeName - dom node name, should be uppercased, e.g. `LABEL` or `SPAN`
```
Comment (ogupte) [inline src/util/dom-helpers.js]: `findNodeName` sounds like a function, maybe rename to just `nodeName`

File: src/util/dom-helpers.js [hunk 3]
```diff
@@ -35,3 +35,30 @@ export function dispatchDOMEvent(node, eventName, assignedEventProps) {
...
+export function sharesAncestor(node, siblingNode, findNodeName) {
+	const nodeName = _.get(node, 'nodeName');
+	const parentNode = _.get(node, 'parentNode');
+
+	if (nodeName === findNodeName) {
+		return node.contains(siblingNode);
+	}
+
+	if (parentNode) {
+		return false || sharesAncestor(parentNode, siblingNode, findNodeName);
```
Comment (mute) [inline src/util/dom-helpers.js]: Seems like the `false ||` might be redundant here -- the recursive call should return either false or the boolean from `node.contains` right?
